services:
  postgres:
    image: postgres:17
    container_name: timekeeper-postgres
    environment:
      POSTGRES_DB: timekeeper_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - timekeeper-postgres:/var/lib/postgresql/data

volumes:
  timekeeper-postgres:
